server:
  port: 8021
spring:
  rabbitmq:
    host: gutsandgun.kro.kr
    port: 11005
    username: gutsandgun
    password: gutsandgun
#    host: 172.16.226.148
#    port: 5672
#    username: solbitest
#    password: solbitest1212!
    virtual-host: gutsandgun
  redis:
    data:
      cluster:
        nodes: redis-cluster.redis.svc.cluster.local:6379
#    port: 6379
#    host: 127.0.0.1
    password:
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://gutsandgun.kro.kr:12002/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #jdbc-url: jdbc:mysql://yjhome.kro.kr:3306/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gutsandgun
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update   # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        show-sql: true
        generate-ddl: true
    open-in-view: false

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace  # query의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여줌
rabbitmq:
  queue1:
    name: SKT
    exchange: SKT-exchange
  queue2:
    name: KT
    exchange: KT-exchange
  queue3:
    name: LG
    exchange: LG-exchange
  routing:
    key:
      queue1: SKT
      queue2: KT
      queue3: LG
feign:
  url :
    broker-dummy1 : https://gutsandgun.kro.kr:45000
    broker-dummy2 : https://gutsandgun.kro.kr:45001
    broker-dummy3 : https://gutsandgun.kro.kr:45002
    sending : https://gutsandgun.kro.kr:30000
#    broker-dummy: gutsandgun.kro.kr:8081
#    sending: gutsandgun.kro.kr:8004